# How has the Philippine labor market changed from 2016 to 2025?
A Philippine Statistics Authority (PSA) Labor and Employment dataset analysis.

## Introduction
### Research Questions
   1. How has the size of the labor force changed?
      - How has the number of Filipinos participating in the labor force changed from 2016 to 2025?
   2. How has employment changed?
      - How has the number of employed Filipinos changed from 2016 to 2025?
   3. How has unemployment changed?
      - How has unemployment changed from 2016 to 2026, particularly before, during, and after the COVID-19 period?
   4. What happened during COVID-19?
      - How did the COVID-19 pandemic affect the Philippine labor market from 2019 to 2021, and how did the labor market recover afterward?
   5. Is there a difference between males and females?
      - How do labor-force participation, employment, and unemployment differ between males and females from 2016 to 2026?
   6. How has underemployment changed?
      - How has underemployment changed from 2016 to 2025, and what does this suggest about employment conditions?

## Dataset

### Source

#### Importing Libraries and Notebook Setup

In [30]:
# pip install pandas numpy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### Loading Data

In [31]:
# Load DataFrame
data_path = 'data.csv'
labor_market = pd.read_csv(data_path, delimiter=';')

### Basic Data Exploration

In [32]:
print(f"Rows count: {labor_market.shape[0]}\nColumns count: {labor_market.shape[1]}")
labor_market.head()

Rows count: 10
Columns count: 17

,Year,Month,Total Population 15 Years Old and Over Both sexes,Total Population 15 Years Old and Over Male,Total Population 15 Years Old and Over Female,Persons in the Labor Force Both sexes,Persons in the Labor Force Male,Persons in the Labor Force Female,Employed Persons Both sexes,Employed Persons Male,Employed Persons Female,Unemployed Persons Both sexes,Unemployed Persons Male,Unemployed Persons Female,Underemployed Persons Both sexes,Underemployed Persons Male,Underemployed Persons Female
0,2016,Annual,68310.620,34184.066,34126.554,43360.939,26521.040,16839.899,40997.968,25034.788,15963.181,2362.970,1486.252,876.719,7512.544,5175.829,2336.715
1,2017,Annual,69890.686,35003.807,34886.879,42774.698,26667.402,16107.296,40333.992,25066.895,15267.097,2440.706,1600.507,840.199,6505.706,4465.670,2040.037
2,2018,Annual,71339.377,35781.919,35557.458,43459.905,26880.358,16579.547,41156.535,25424.309,15732.226,2303.371,1456.049,847.322,6734.331,4597.185,2137.146
3,2019,Annual,72143.459,36223.025,35920.435,44197.118,27104.740,17092.379,41938.013,25697.921,16240.092,2259.106,1406.819,852.287,5778.283,3928.176,1850.107
4,2020,Annual,73732.465,37029.448,36703.017,43878.159,27049.834,16828.325,39377.842,24179.071,15198.771,4500.318,2870.763,1629.554,6395.121,4327.980,2067.141

#### Check Data Types

In [33]:
labor_market.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 17 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Year                                               10 non-null     int64
 1   Month                                              10 non-null     str
 2   Total Population 15 Years Old and Over Both sexes  10 non-null     float64
 3   Total Population 15 Years Old and Over Male        10 non-null     float64
 4   Total Population 15 Years Old and Over Female      10 non-null     float64
 5   Persons in the Labor Force Both sexes              10 non-null     float64
 6   Persons in the Labor Force Male                    10 non-null     float64
 7   Persons in the Labor Force Female                  10 non-null     float64
 8   Employed Persons Both sexes                        10 non-null     float64
 9   Employed Persons Male                              10 non-null     float64
 10  Employed Persons Female                            10 non-null     float64
 11  Unemployed Persons Both sexes                      10 non-null     float64
 12  Unemployed Persons Male                            10 non-null     float64
 13  Unemployed Persons Female                          10 non-null     float64
 14  Underemployed Persons Both sexes                   10 non-null     float64
 15  Underemployed Persons Male                         10 non-null     float64
 16  Underemployed Persons Female                       10 non-null     float64
dtypes: float64(15), int64(1), str(1)
memory usage: 1.5 KB

#### Check Missing Data

In [34]:
missing_percent = labor_market.isna().mean().sort_values(ascending=False)
print('---- Percentage of Missing Values (%) -----')
if missing_percent.sum():
    print(missing_percent[missing_percent > 0] * 100)
else:
    print('None')

---- Percentage of Missing Values (%) -----
None

#### Check Duplicate Rows

In [35]:
# Show number of duplicated rows
print(f"No. of entirely duplicated rows: {labor_market.duplicated().sum()}")

No. of entirely duplicated rows: 0

#### Check Uniqueness Data

In [36]:
# Print the percentage similarity of values (the lower %, the better)
num_unique = labor_market.nunique().sort_values()
print('---- Percentage Similarity of Values (%) -----')
print(100/num_unique)

---- Percentage Similarity of Values (%) -----
Month                                                100.0
Year                                                  10.0
Underemployed Persons Both sexes                      10.0
Unemployed Persons Female                             10.0
Unemployed Persons Male                               10.0
Unemployed Persons Both sexes                         10.0
Employed Persons Female                               10.0
Employed Persons Male                                 10.0
Employed Persons Both sexes                           10.0
Persons in the Labor Force Female                     10.0
Persons in the Labor Force Male                       10.0
Persons in the Labor Force Both sexes                 10.0
Total Population 15 Years Old and Over Female         10.0
Total Population 15 Years Old and Over Male           10.0
Total Population 15 Years Old and Over Both sexes     10.0
Underemployed Persons Male                            10.0
Underemployed Persons Female                          10.0
dtype: float64

### Exploratory Data Analysis

#### Labor Force

In [37]:
Persons_In_The_Labor_Force_Female_By_Year = labor_market[['Year', 'Persons in the Labor Force Female']]
Persons_In_The_Labor_Force_Male_By_Year = labor_market['Persons in the Labor Force Male']
Persons_In_The_Labor_Force_Both_sexes = labor_market['Persons in the Labor Force Both sexes']

##### Persons in the Labor Force Female By Year

In [38]:
Persons_In_The_Labor_Force_Female_By_Year.info()
Persons_In_The_Labor_Force_Female_By_Year.head()
#Persons_In_The_Labor_Force_Female_By_Year.tail()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Year                               10 non-null     int64
 1   Persons in the Labor Force Female  10 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 292.0 bytes

   Year  Persons in the Labor Force Female
0  2016                          16839.899
1  2017                          16107.296
2  2018                          16579.547
3  2019                          17092.379
4  2020                          16828.325

##### Persons in the Labor Force Male By Year

In [39]:
Persons_In_The_Labor_Force_Male_By_Year.info()
Persons_In_The_Labor_Force_Male_By_Year.head()

<class 'pandas.Series'>
RangeIndex: 10 entries, 0 to 9
Series name: Persons in the Labor Force Male
Non-Null Count  Dtype
--------------  -----
10 non-null     float64
dtypes: float64(1)
memory usage: 212.0 bytes

0    26521.040
1    26667.402
2    26880.358
3    27104.740
4    27049.834
Name: Persons in the Labor Force Male, dtype: float64

##### Persons in the Labor Force Both sexes

In [40]:
Persons_In_The_Labor_Force_Both_sexes.info()
Persons_In_The_Labor_Force_Both_sexes.head()

<class 'pandas.Series'>
RangeIndex: 10 entries, 0 to 9
Series name: Persons in the Labor Force Both sexes
Non-Null Count  Dtype
--------------  -----
10 non-null     float64
dtypes: float64(1)
memory usage: 212.0 bytes

0    43360.939
1    42774.698
2    43459.905
3    44197.118
4    43878.159
Name: Persons in the Labor Force Both sexes, dtype: float64